// Generated by Triple Speed Ethernet 9.1 [Altera, IP Toolbench 1.3.0 Build 350]
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2011 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.

module sfp2gmii (
	gmii_rx_d,
	gmii_rx_dv,
	gmii_rx_err,
	tx_clk,
	rx_clk,
	readdata,
	waitrequest,
	txp,
	reconfig_fromgxb,
	led_an,
	led_disp_err,
	led_char_err,
	led_link,
	gmii_tx_d,
	gmii_tx_en,
	gmii_tx_err,
	reset_tx_clk,
	reset_rx_clk,
	address,
	read,
	writedata,
	write,
	clk,
	reset,
	rxp,
	ref_clk,
	reconfig_clk,
	reconfig_togxb,
	gxb_cal_blk_clk);

	output	[7:0]	gmii_rx_d;
	output		gmii_rx_dv;
	output		gmii_rx_err;
	output		tx_clk;
	output		rx_clk;
	output	[15:0]	readdata;
	output		waitrequest;
	output		txp;
	output	[16:0]	reconfig_fromgxb;
	output		led_an;
	output		led_disp_err;
	output		led_char_err;
	output		led_link;
	input	[7:0]	gmii_tx_d;
	input		gmii_tx_en;
	input		gmii_tx_err;
	input		reset_tx_clk;
	input		reset_rx_clk;
	input	[4:0]	address;
	input		read;
	input	[15:0]	writedata;
	input		write;
	input		clk;
	input		reset;
	input		rxp;
	input		ref_clk;
	input		reconfig_clk;
	input	[3:0]	reconfig_togxb;
	input		gxb_cal_blk_clk;
endmodule
